---
abstract: "easy access to data in many formats"
author:
  - 'Jeff Zucker (jeff@vpservices.com)'
  - 'Sven Dowideit (SvenDowideit@fosiki.com)'
build_requires:
  Test::More: 0.9
  Test::Output: 0.01
  Test::Pod::Spelling::CommonMistakes: 1.000
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyData
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  homepage: http://github.com/SvenDowideit/Data-Foswiki
  repository: git://github.com/SvenDowideit/Data-Foswiki.git
version: 0.10_50TRIAL
